@echo off
title Lanzador - Calculadora de Metodos Numericos
echo Cargando entorno de Python...
echo Verificando dependencias...
python -m pip install -r requirements.txt --quiet
echo Iniciando aplicacion Streamlit...
python -m streamlit run app.py
pause
